// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: balance_sheets.sql

package sqlc_generated

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBalanceSheetRecord = `-- name: CreateBalanceSheetRecord :one
INSERT INTO balance_sheets (
id, 
ticker, 
fiscal_date_ending, 
total_assets, 
intangible_assets, 
total_liabilities,
common_stock,
common_stock_shares_outstanding,
created_on,
updated_on
)
VALUES($1,$2,$3,$4,$5,$6,$7,$8, $9, $10)
RETURNING id, ticker, fiscal_date_ending, total_assets, intangible_assets, total_liabilities, common_stock, common_stock_shares_outstanding, created_on, updated_on
`

type CreateBalanceSheetRecordParams struct {
	ID                           uuid.UUID
	Ticker                       string
	FiscalDateEnding             time.Time
	TotalAssets                  int64
	IntangibleAssets             int64
	TotalLiabilities             int64
	CommonStock                  int64
	CommonStockSharesOutstanding int64
	CreatedOn                    time.Time
	UpdatedOn                    time.Time
}

func (q *Queries) CreateBalanceSheetRecord(ctx context.Context, arg CreateBalanceSheetRecordParams) (BalanceSheet, error) {
	row := q.db.QueryRowContext(ctx, createBalanceSheetRecord,
		arg.ID,
		arg.Ticker,
		arg.FiscalDateEnding,
		arg.TotalAssets,
		arg.IntangibleAssets,
		arg.TotalLiabilities,
		arg.CommonStock,
		arg.CommonStockSharesOutstanding,
		arg.CreatedOn,
		arg.UpdatedOn,
	)
	var i BalanceSheet
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.FiscalDateEnding,
		&i.TotalAssets,
		&i.IntangibleAssets,
		&i.TotalLiabilities,
		&i.CommonStock,
		&i.CommonStockSharesOutstanding,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const deleteBalanceSheetRecordsByTicker = `-- name: DeleteBalanceSheetRecordsByTicker :exec
DELETE from balance_sheets
WHERE ticker = $1
`

func (q *Queries) DeleteBalanceSheetRecordsByTicker(ctx context.Context, ticker string) error {
	_, err := q.db.ExecContext(ctx, deleteBalanceSheetRecordsByTicker, ticker)
	return err
}

const getBalanceSheetRecordsByTicker = `-- name: GetBalanceSheetRecordsByTicker :many
SELECT id, ticker, fiscal_date_ending, total_assets, intangible_assets, total_liabilities, common_stock, common_stock_shares_outstanding, created_on, updated_on from balance_sheets
WHERE ticker = $1
`

func (q *Queries) GetBalanceSheetRecordsByTicker(ctx context.Context, ticker string) ([]BalanceSheet, error) {
	rows, err := q.db.QueryContext(ctx, getBalanceSheetRecordsByTicker, ticker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceSheet
	for rows.Next() {
		var i BalanceSheet
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.FiscalDateEnding,
			&i.TotalAssets,
			&i.IntangibleAssets,
			&i.TotalLiabilities,
			&i.CommonStock,
			&i.CommonStockSharesOutstanding,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
