// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc_generated

import (
	"time"

	"github.com/google/uuid"
)

type BalanceSheet struct {
	ID                           uuid.UUID
	Ticker                       string
	FiscalDateEnding             time.Time
	TotalAssets                  int64
	IntangibleAssets             int64
	TotalLiabilities             int64
	CommonStock                  int64
	CommonStockSharesOutstanding int64
	CreatedOn                    time.Time
	UpdatedOn                    time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	Token     string
	ExpiresOn time.Time
	CreatedOn time.Time
	UpdatedOn time.Time
	UserID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	IsAdmin        bool
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
