// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_tokens.sql

package sqlc_generated

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, token, expires_on, created_on, updated_on)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token, expires_on, created_on, updated_on
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	Token     string
	ExpiresOn time.Time
	CreatedOn time.Time
	UpdatedOn time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.ID,
		arg.Token,
		arg.ExpiresOn,
		arg.CreatedOn,
		arg.UpdatedOn,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresOn,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const deleteRefreshTokenById = `-- name: DeleteRefreshTokenById :exec
DELETE FROM refresh_tokens
WHERE refresh_tokens.id = $1
`

func (q *Queries) DeleteRefreshTokenById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokenById, id)
	return err
}

const getRefreshTokenInfoByToken = `-- name: GetRefreshTokenInfoByToken :one
SELECT refresh_tokens.id, refresh_tokens.token, refresh_tokens.expires_on
  FROM refresh_tokens
  WHERE refresh_tokens.token = $1
`

type GetRefreshTokenInfoByTokenRow struct {
	ID        uuid.UUID
	Token     string
	ExpiresOn time.Time
}

func (q *Queries) GetRefreshTokenInfoByToken(ctx context.Context, token string) (GetRefreshTokenInfoByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenInfoByToken, token)
	var i GetRefreshTokenInfoByTokenRow
	err := row.Scan(&i.ID, &i.Token, &i.ExpiresOn)
	return i, err
}
